// Generated 15 Oct 2019 20:23 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using System.Data;
using System.Data.SqlClient;
using Csla;
using Csla.Data;
using Singular;


namespace OETLib.Server.General
{
  [Serializable]
  public class GeneralSecurityGroupUserList
   : SingularBusinessListBase<GeneralSecurityGroupUserList, GeneralSecurityGroupUser>
  {
    #region " Business Methods "

    public GeneralSecurityGroupUser GetItem(int SecurityGroupUserID)
    {
      foreach (GeneralSecurityGroupUser child in this)
      {
        if (child.SecurityGroupUserID == SecurityGroupUserID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "S";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static GeneralSecurityGroupUserList NewGeneralSecurityGroupUserList()
    {
      return new GeneralSecurityGroupUserList();
    }

    public GeneralSecurityGroupUserList()
    {
      // must have parameter-less constructor
    }

    public static GeneralSecurityGroupUserList GetGeneralSecurityGroupUserList()
    {
      return DataPortal.Fetch<GeneralSecurityGroupUserList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      while (sdr.Read())
      {
        this.Add(GeneralSecurityGroupUser.GetGeneralSecurityGroupUser(sdr));
      }
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getGeneralSecurityGroupUserList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}