USE [master]
GO

/****** Object:  Database [OfficeExpressTuckShop]    Script Date: 28/05/2019 21:04:08 ******/
CREATE DATABASE [OfficeExpressTuckShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Data', FILENAME = N'C:\Data\OfficeExpressTuckShop.mdf' , SIZE = 13312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10240KB )
 LOG ON 
( NAME = N'Log', FILENAME = N'C:\Data\OfficeExpressTuckShop.ldf' , SIZE = 14912KB , MAXSIZE = 2048GB , FILEGROWTH = 10240KB )
GO

ALTER DATABASE [OfficeExpressTuckShop] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OfficeExpressTuckShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OfficeExpressTuckShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET RECOVERY FULL 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET  MULTI_USER 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OfficeExpressTuckShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OfficeExpressTuckShop] SET QUERY_STORE = OFF
GO

USE [OfficeExpressTuckShop]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [OfficeExpressTuckShop] SET  READ_WRITE 
GO

