// Generated 05 Mar 2019 08:48 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace OETLib.BusinessObjects.Model
{
    [Serializable]
    public class EditInventoryList
     : SingularBusinessListBase<EditInventoryList, EditInventory>
    {
        #region " Business Methods "

        public EditInventory GetItem(string ProductName)
        {
            foreach (EditInventory child in this)
            {
                if (child.ProductName == ProductName)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "S";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

        }

        public static EditInventoryList NewEditInventoryList()
        {
            return new EditInventoryList();
        }

        public EditInventoryList()
        {
            // must have parameter-less constructor
        }

        public static EditInventoryList GetEditInventoryList()
        {
            return DataPortal.Fetch<EditInventoryList>(new Criteria());
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(EditInventory.GetEditInventory(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        cm.CommandText = "GetProcs.getEditInventoryList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}