// Generated 26 Jul 2019 07:53 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using System.Data;
using System.Data.SqlClient;
using Csla;
using Csla.Data;
using Singular;


namespace OETLib.BusinessObjects.Model
{
  [Serializable]
  public class InvoiceList
   : SingularBusinessListBase<InvoiceList, Invoice>
  {
    #region " Business Methods "

    public Invoice GetItem(int InvoiceID)
    {
      foreach (Invoice child in this)
      {
        if (child.InvoiceID == InvoiceID)
        {
          return child;
        }
      }
      return null;
    }

    public override string ToString()
    {
      return "Invoices";
    }

    #endregion

    #region " Data Access "

    [Serializable]
    public class Criteria
      : CriteriaBase<Criteria>
    {
      public Criteria()
      {
      }

    }

    public static InvoiceList NewInvoiceList()
    {
      return new InvoiceList();
    }

    public InvoiceList()
    {
      // must have parameter-less constructor
    }

    public static InvoiceList GetInvoiceList()
    {
      return DataPortal.Fetch<InvoiceList>(new Criteria());
    }

    protected void Fetch(SafeDataReader sdr)
    {
      this.RaiseListChangedEvents = false;
      while (sdr.Read())
      {
        this.Add(Invoice.GetInvoice(sdr));
      }
      this.RaiseListChangedEvents = true;
    }

    protected override void DataPortal_Fetch(Object criteria)
    {
      Criteria crit = (Criteria)criteria;
      using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
      {
        cn.Open();
        try
        {
          using (SqlCommand cm = cn.CreateCommand())
          {
            cm.CommandType = CommandType.StoredProcedure;
            cm.CommandText = "GetProcs.getInvoiceList";
            using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
            {
              Fetch(sdr);
            }
          }
        }
        finally
        {
          cn.Close();
        }
      }
    }

    #endregion

  }

}