// Generated 21 Feb 2019 14:50 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace OETLib.BusinessObjects.Model
{
    [Serializable]
    public class myCart
     : SingularBusinessBase<myCart>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> OrderIDProperty = RegisterProperty<int>(c => c.OrderID, "ID");
        /// <summary>
        /// Gets and sets the ID value
        /// </summary>
        [Display(Name = "ID", Description = ""),
        Required(ErrorMessage = "ID required")]
        public int OrderID
        {
            get { return GetProperty(OrderIDProperty); }
            set { SetProperty(OrderIDProperty, value); }
        }

        public static PropertyInfo<int> UserIDProperty = RegisterProperty<int>(c => c.UserID, "User");
        /// <summary>
        /// Gets and sets the User value
        /// </summary>
        [Display(Name = "User", Description = ""),
        Required(ErrorMessage = "User required")]
        public int UserID
        {
            get { return GetProperty(UserIDProperty); }
            set { SetProperty(UserIDProperty, value); }
        }

        public static PropertyInfo<int> ProductIDProperty = RegisterProperty<int>(c => c.ProductID, "Product");
        /// <summary>
        /// Gets and sets the Product value
        /// </summary>
        [Display(Name = "Product", Description = ""),
        Required(ErrorMessage = "Product required")]
        public int ProductID
        {
            get { return GetProperty(ProductIDProperty); }
            set { SetProperty(ProductIDProperty, value); }
        }

        public static PropertyInfo<int> ProductQuantityProperty = RegisterProperty<int>(c => c.ProductQuantity, "Product Quantity");
        /// <summary>
        /// Gets and sets the Product Quantity value
        /// </summary>
        [Display(Name = "Product Quantity", Description = ""),
        Required(ErrorMessage = "Product Quantity required")]
        public int ProductQuantity
        {
            get { return GetProperty(ProductQuantityProperty); }
            set { SetProperty(ProductQuantityProperty, value); }
        }

        public static PropertyInfo<decimal> UnitPriceProperty = RegisterProperty<decimal>(c => c.UnitPrice, "Unit Price");
        /// <summary>
        /// Gets and sets the Unit Price value
        /// </summary>
        [Display(Name = "Unit Price", Description = ""),
        Required(ErrorMessage = "Unit Price required")]
        public decimal UnitPrice
        {
            get { return GetProperty(UnitPriceProperty); }
            set { SetProperty(UnitPriceProperty, value); }
        }

        public static PropertyInfo<int> OrderDetailsIDProperty = RegisterProperty<int>(c => c.OrderDetailsID, "ID");
        /// <summary>
        /// Gets and sets the ID value
        /// </summary>
        [Display(Name = "Product Name", Description = ""),
        Required(ErrorMessage = "ID required")]
        public int OrderDetailsID
        {
            get { return GetProperty(OrderDetailsIDProperty); }
            set { SetProperty(OrderDetailsIDProperty, value); }
        }

        public static PropertyInfo<string> ProductNameProperty = RegisterProperty<string>(c => c.ProductName, "Product Name");
        /// <summary>
        /// Gets and sets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key,
        Required(ErrorMessage = "Product name required")]
        public string ProductName
        {
            get { return GetProperty(ProductNameProperty); }
            set { SetProperty(ProductNameProperty, value); }
        }

        public static PropertyInfo<DateTime> OrderDateProperty = RegisterProperty<DateTime>(c => c.OrderDate, "Order date");
        /// <summary>
        /// Gets and sets the ID value
        /// </summary>
        [Display(Name = "Order date", Description = ""),
         Required(ErrorMessage = "Order Date required")]
        public DateTime OrderDate
        {
            get { return GetProperty(OrderDateProperty); }
            set { SetProperty(OrderDateProperty, value); }
        }

        public static PropertyInfo<int> ProcessStatusIDProperty = RegisterProperty<int>(c => c.ProcessStatusID, "Process Status");
        /// <summary>
        /// Gets and sets the Process Status value
        /// </summary>
        [Display(Name = "Process Status", Description = ""),
        Required(ErrorMessage = "Process Status required")]
        public int ProcessStatusID
        {
            get { return GetProperty(ProcessStatusIDProperty); }
            set { SetProperty(ProcessStatusIDProperty, value); }
        }

        public static PropertyInfo<Decimal> ProductPriceProperty = RegisterProperty<Decimal>(c => c.ProductPrice, "Product Price");
        [Display(Name = "Product Price", Description = ""),
        Required(ErrorMessage = "Productprice required")]
        public Decimal ProductPrice
        {
            get { return GetProperty(ProductPriceProperty); }
            set { SetProperty(ProductPriceProperty, value); }
        }

        // public decimal TotalPrice { get { return this.UnitPrice * this.ProductQuantity; } }
        public decimal TotalPrice { get { return this.ProductQuantity*this.ProductPrice; } }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(OrderDetailsIDProperty);
        }

        public override string ToString()
        {
            if (this.OrderDetailsID.ToString().Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "My Cart");
                }
                else
                {
                    return String.Format("Blank {0}", "My Cart");
                }
            }
            else
            {
                return this.OrderDetailsID.ToString();
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewmyCart() method.
        }

        public static myCart NewmyCart()
        {
            return DataPortal.CreateChild<myCart>();
        }

        public myCart()
        {
            MarkAsChild();
        }

        internal static myCart GetmyCart(SafeDataReader dr)
        {
            var m = new myCart();
            m.Fetch(dr);
            return m;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(OrderIDProperty, sdr.GetInt32(i++));
                LoadProperty(UserIDProperty, Singular.Misc.ZeroNothing(sdr.GetInt32(i++)));
                LoadProperty(ProductIDProperty, Singular.Misc.ZeroNothing(sdr.GetInt32(i++)));
                LoadProperty(ProductQuantityProperty, sdr.GetInt32(i++));
                LoadProperty(UnitPriceProperty, sdr.GetDecimal(i++));
                LoadProperty(OrderDetailsIDProperty, Singular.Misc.ZeroNothing(sdr.GetInt32(i++)));
                LoadProperty(ProductNameProperty, sdr.GetValue(i++));
                LoadProperty(OrderDateProperty, sdr.GetValue(i++));
                LoadProperty(ProcessStatusIDProperty, sdr.GetInt32(i++));
                LoadProperty(ProductPriceProperty, sdr.GetDecimal(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@OrderID", GetProperty(OrderIDProperty));
            cm.Parameters.AddWithValue("@UserID", GetProperty(UserIDProperty));
            cm.Parameters.AddWithValue("@ProductID", GetProperty(ProductIDProperty));
            cm.Parameters.AddWithValue("@ProductQuantity", GetProperty(ProductQuantityProperty));
            cm.Parameters.AddWithValue("@UnitPrice", GetProperty(UnitPriceProperty));
            cm.Parameters.AddWithValue("@ProductName", GetProperty(ProductNameProperty));
            cm.Parameters.AddWithValue("@OrderDate", GetProperty(OrderDateProperty));
            cm.Parameters.AddWithValue("@ProcessStatusID", GetProperty(ProcessStatusIDProperty));
            AddPrimaryKeyParam(cm, OrderDetailsIDProperty);
            cm.Parameters.AddWithValue("@ProductPrice", GetProperty(ProductPriceProperty));


            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(OrderDetailsIDProperty, scm.Parameters["@OrderDetailsID"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@OrderDetailsID", GetProperty(OrderDetailsIDProperty));
        }

        #endregion

    }

}