// Generated 21 Feb 2019 14:50 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace OETLib.BusinessObjects.Model
{
    [Serializable]
    public class myCartList
     : SingularBusinessListBase<myCartList, myCart>
    {
        #region " Business Methods "

        public myCart GetItem(int OrderID)
        {
            foreach (myCart child in this)
            {
                if (child.OrderID == OrderID)
                {
                    return child;
                }
            }
            return null;
        }

        public override string ToString()
        {
            return "S";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }
            public int? _userid { get; set; }

        }

        public static myCartList NewmyCartList()
        {
            return new myCartList();
        }

        public myCartList()
        {
            // must have parameter-less constructor
        }

        public static myCartList GetmyCartList()
        {
            return DataPortal.Fetch<myCartList>(new Criteria());
        }

        public static myCartList GetmyCartList(int userid)
        {
            return DataPortal.Fetch<myCartList>(new Criteria { _userid = userid });
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(myCart.GetmyCart(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        //custom stored proc code
                        if (crit._userid.HasValue)
                            cm.Parameters.AddWithValue("@userid", crit._userid);

                        cm.CommandText = "GetProcs.getmyCartList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}