// Generated 26 Feb 2019 15:11 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace OETLib.BusinessObjects.Model
{
    [Serializable]
    public class UserOrdersList
     : SingularBusinessListBase<UserOrdersList, UserOrders>
    {
        #region " Business Methods "

        public UserOrders GetItem(int OrderID)
        {
            foreach (UserOrders child in this)
            {
                if (child.OrderID == OrderID)
                {
                    return child;
                }
            }
            return null;
        }

        

        public override string ToString()
        {
            return "S";
        }

        #endregion

        #region " Data Access "

        [Serializable]
        public class Criteria
          : CriteriaBase<Criteria>
        {
            public Criteria()
            {
            }

            public int? ProcessStatusID { get; set; }
        }

        public static UserOrdersList NewUserOrdersList()
        {
            return new UserOrdersList();
        }

        public UserOrdersList()
        {
            // must have parameter-less constructor
        }

        public static UserOrdersList GetUserOrdersList()
        {
            return DataPortal.Fetch<UserOrdersList>(new Criteria());
        }

        public static UserOrdersList GetUserOrdersList(int processStatusID)
        {
            return DataPortal.Fetch<UserOrdersList>(new Criteria { ProcessStatusID=processStatusID });
        }

        protected void Fetch(SafeDataReader sdr)
        {
            this.RaiseListChangedEvents = false;
            while (sdr.Read())
            {
                this.Add(UserOrders.GetUserOrders(sdr));
            }
            this.RaiseListChangedEvents = true;
        }

        protected override void DataPortal_Fetch(Object criteria)
        {
            Criteria crit = (Criteria)criteria;
            using (SqlConnection cn = new SqlConnection(Singular.Settings.ConnectionString))
            {
                cn.Open();
                try
                {
                    using (SqlCommand cm = cn.CreateCommand())
                    {
                        cm.CommandType = CommandType.StoredProcedure;
                        //Custom stored procfals
                        if (crit.ProcessStatusID.HasValue)
                            cm.Parameters.AddWithValue("@ProcessStatusID", crit.ProcessStatusID);
                        
                        cm.CommandText = "GetProcs.getUserOrdersList";
                        using (SafeDataReader sdr = new SafeDataReader(cm.ExecuteReader()))
                        {
                            Fetch(sdr);
                        }
                    }
                }
                finally
                {
                    cn.Close();
                }
            }
        }

        #endregion

    }

}