// Generated 26 Feb 2019 15:11 - Singular Systems Object Generator Version 2.2.699
//<auto-generated/>
using System;
using Csla;
using Csla.Serialization;
using Csla.Data;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using Singular;
using Singular.DataAnnotations;
using System.Data;
using System.Data.SqlClient;


namespace OETLib.BusinessObjects.Model
{
    [Serializable]
    public class UserOrders
     : SingularBusinessBase<UserOrders>
    {
        #region " Properties and Methods "

        #region " Properties "

        public static PropertyInfo<int> OrderIDProperty = RegisterProperty<int>(c => c.OrderID, "ID");
        /// <summary>
        /// Gets and sets the ID value
        /// </summary>
        [Display(AutoGenerateField = false), Key,
        Required(ErrorMessage = "ID required")]
        public int OrderID
        {
            get { return GetProperty(OrderIDProperty); }
            set { SetProperty(OrderIDProperty, value); }
        }

        public static PropertyInfo<string> ProductNameProperty = RegisterProperty<string>(c => c.ProductName, "Product Name");
        /// <summary>
        /// Gets and sets the Product Name value
        /// </summary>
        [Display(Name = "Product Name", Description = "")]
        public string ProductName
        {
            get { return GetProperty(ProductNameProperty); }
            set { SetProperty(ProductNameProperty, value); }
        }

        public static PropertyInfo<int> ProductIDProperty = RegisterProperty<int>(c => c.ProductID, "Product Name");
        /// <summary>
        /// Gets and sets the Product Name value
        /// </summary>
        [Display(Name = "ProductID", Description = "")]
        public int ProductID
        {
            get { return GetProperty(ProductIDProperty); }
            set { SetProperty(ProductIDProperty, value); }
        }

        public static PropertyInfo<string> FirstNameProperty = RegisterProperty<string>(c => c.FirstName, "First Name");
        /// <summary>
        /// Gets and sets the First Name value
        /// </summary>
        [Display(Name = "First Name", Description = "")]
        public string FirstName
        {
            get { return GetProperty(FirstNameProperty); }
            set { SetProperty(FirstNameProperty, value); }
        }

        public static PropertyInfo<string> LastNameProperty = RegisterProperty<string>(c => c.LastName, "Last Name");
        /// <summary>
        /// Gets and sets the Last Name value
        /// </summary>
        [Display(Name = "Last Name", Description = "")]
        public string LastName
        {
            get { return GetProperty(LastNameProperty); }
            set { SetProperty(LastNameProperty, value); }
        }

        public static PropertyInfo<int> ProductQuantityProperty = RegisterProperty<int>(c => c.ProductQuantity, "Product Quantity");
        /// <summary>
        /// Gets and sets the Product Quantity value
        /// </summary>
        [Display(Name = "Product Quantity", Description = ""),
        Required(ErrorMessage = "Product Quantity required")]
        public int ProductQuantity
        {
            get { return GetProperty(ProductQuantityProperty); }
            set { SetProperty(ProductQuantityProperty, value); }
        }

        public static PropertyInfo<decimal> UnitPriceProperty = RegisterProperty<decimal>(c => c.UnitPrice, "Unit Price");
        /// <summary>
        /// Gets and sets the Unit Price value
        /// </summary>
        [Display(Name = "Unit Price", Description = ""),
        Required(ErrorMessage = "Unit Price required")]
        public decimal UnitPrice
        {
            get { return GetProperty(UnitPriceProperty); }
            set { SetProperty(UnitPriceProperty, value); }
        }

        public static PropertyInfo<DateTime> OrderDateProperty = RegisterProperty<DateTime>(c => c.OrderDate, "Order Date");
        /// <summary>
        /// Gets and sets the Order Date value
        /// </summary>
        [Display(Name = "Order Date", Description = ""),
        Required(ErrorMessage = "Order Date required")]
        public DateTime OrderDate
        {
            get
            {
                return GetProperty(OrderDateProperty);
            }
            set
            {
                SetProperty(OrderDateProperty, value);
            }
        }

        public static PropertyInfo<DateTime> RequiredDateProperty = RegisterProperty<DateTime>(c => c.RequiredDate, "Required Date");
        /// <summary>
        /// Gets and sets the Required Date value
        /// </summary>
        [Display(Name = "Required Date", Description = ""),
        Required(ErrorMessage = "Required Date required")]
        public DateTime RequiredDate
        {
            get
            {
                return GetProperty(RequiredDateProperty);
            }
            set
            {
                SetProperty(RequiredDateProperty, value);
            }
        }

        public static PropertyInfo<int> ProcessStatusIDProperty = RegisterProperty<int>(c => c.ProcessStatusID, "Process Status", 0);
        /// <summary>
        /// Gets and sets the Process Status value
        /// </summary>
        [Display(Name = "Process Status", Description = ""),
        Required(ErrorMessage = "Process Status required")]
        public int ProcessStatusID
        {
            get { return GetProperty(ProcessStatusIDProperty); }
            set { SetProperty(ProcessStatusIDProperty, value); }
        }

        
             public static PropertyInfo<int> UserIDProperty = RegisterProperty<int>(c => c.UserID, "User ID");
        /// <summary>
        /// Gets and sets the Process Status value
        /// </summary>
        [Display(Name = "User ID", Description = ""),
        Required(ErrorMessage = "User ID required")]
        public int UserID
        {
            get { return GetProperty(UserIDProperty); }
            set { SetProperty(UserIDProperty, value); }
        }

        #endregion

        #region " Methods "

        protected override object GetIdValue()
        {
            return GetProperty(OrderIDProperty);
        }

        public override string ToString()
        {
            if (this.ProductName.Length == 0)
            {
                if (this.IsNew)
                {
                    return String.Format("New {0}", "User Orders");
                }
                else
                {
                    return String.Format("Blank {0}", "User Orders");
                }
            }
            else
            {
                return this.ProductName;
            }
        }

        #endregion

        #endregion

        #region " Validation Rules "

        protected override void AddBusinessRules()
        {
            base.AddBusinessRules();
        }

        #endregion

        #region " Data Access & Factory Methods "

        protected override void OnCreate()
        {
            // This is called when a new object is created
            // Set any variables here, not in the constructor or NewUserOrders() method.
        }

        public static UserOrders NewUserOrders()
        {
            return DataPortal.CreateChild<UserOrders>();
        }

        public UserOrders()
        {
            MarkAsChild();
        }

        internal static UserOrders GetUserOrders(SafeDataReader dr)
        {
            var u = new UserOrders();
            u.Fetch(dr);
            return u;
        }

        protected void Fetch(SafeDataReader sdr)
        {
            using (BypassPropertyChecks)
            {
                int i = 0;
                LoadProperty(OrderIDProperty, sdr.GetInt32(i++));
                LoadProperty(ProductNameProperty, sdr.GetString(i++));
                LoadProperty(FirstNameProperty, sdr.GetString(i++));
                LoadProperty(LastNameProperty, sdr.GetString(i++));
                LoadProperty(ProductQuantityProperty, sdr.GetInt32(i++));
                LoadProperty(UnitPriceProperty, sdr.GetDecimal(i++));
                LoadProperty(OrderDateProperty, sdr.GetValue(i++));
                LoadProperty(RequiredDateProperty, sdr.GetValue(i++));
                LoadProperty(ProcessStatusIDProperty, sdr.GetInt32(i++));
                LoadProperty(ProductIDProperty, sdr.GetInt32(i++));
                LoadProperty(UserIDProperty, sdr.GetInt32(i++));
            }

            MarkAsChild();
            MarkOld();
            BusinessRules.CheckRules();
        }

        protected override Action<SqlCommand> SetupSaveCommand(SqlCommand cm)
        {
            AddPrimaryKeyParam(cm, OrderIDProperty);

            cm.Parameters.AddWithValue("@ProductName", GetProperty(ProductNameProperty));
            cm.Parameters.AddWithValue("@FirstName", GetProperty(FirstNameProperty));
            cm.Parameters.AddWithValue("@LastName", GetProperty(LastNameProperty));
            cm.Parameters.AddWithValue("@ProductQuantity", GetProperty(ProductQuantityProperty));
            cm.Parameters.AddWithValue("@UnitPrice", GetProperty(UnitPriceProperty));
            cm.Parameters.AddWithValue("@OrderDate", OrderDate);
            cm.Parameters.AddWithValue("@RequiredDate", RequiredDate);
            cm.Parameters.AddWithValue("@ProcessStatusID", GetProperty(ProcessStatusIDProperty));
            cm.Parameters.AddWithValue("@ProductID", GetProperty(ProductIDProperty));
            cm.Parameters.AddWithValue("@UserID", GetProperty(UserIDProperty));


            return (scm) =>
            {
    // Post Save
    if (this.IsNew)
                {
                    LoadProperty(OrderIDProperty, scm.Parameters["@OrderID"].Value);
                }
            };
        }

        protected override void SaveChildren()
        {
            // No Children
        }

        protected override void SetupDeleteCommand(SqlCommand cm)
        {
            cm.Parameters.AddWithValue("@OrderID", GetProperty(OrderIDProperty));
        }

        #endregion

    }

}